import org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    ext {
        kotlin_version = '2.2.20'
        ksp_version = '2.2.20-2.0.4'
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
        classpath "com.google.devtools.ksp:symbol-processing-api:$ksp_version"
        classpath "com.google.devtools.ksp:symbol-processing-gradle-plugin:$ksp_version"
        classpath 'com.google.gms:google-services:4.5.0'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.7'
    }
}

tasks.register('clean', Delete) {
    delete getLayout().getBuildDirectory()
}


tasks.withType(KotlinJvmCompile).configureEach {
    compilerOptions {
        freeCompilerArgs.add("-opt-in=kotlin.RequiresOptIn")
    }
}
